# Sample of dtvault-central.config.toml

# gRPC サーバ設定
[server]
# Listen するポート
listen = "[::0]:50051"

[database]
data_dir = "/var/lib/dtvault/data"

[[storages]]
driver = "FileSystem"
root_dir = "/var/lib/dtvault/storage"
